disabled_rules: # rule identifiers to exclude from running
  - closure_parameter_position
  - opening_brace
  - redundant_string_enum_value
  - cyclomatic_complexity
  - superfluous_disable_command

opt_in_rules:
 - force_unwrapping

file_length:
  warning: 1000
  error: 2000

type_body_length:
  warning: 3000
  error: 4000

function_body_length:
  warning: 100
  error: 200

line_length:
  warning: 200
  error: 300

identifier_name:
  min_length:
    warning: 0
    error: 0
  excluded: # excluded via string array
    - id

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  severity: error

